### ISSUE TITLE
metal_plan_info

### ISSUE THREAD

**Issue by t0mk** [equinix-labs/ansible-collection-equinix#136]
Module for listing plans

https://deploy.equinix.com/developers/api/metal/#tag/Plans/operation/findPlans

We had sth like that in the old collection:

https://github.com/equinix/ansible-collection-metal/blob/main/docs/equinix.metal.plan_info_module.rst

**Comment by t0mk** [comment]
Ansible wrapper of
https://github.com/equinix-labs/metal-python/blob/main/equinix_metal/equinix_metal/api/plans_api.py#L50

which is a wrapper of:
https://deploy.equinix.com/developers/api/metal/#tag/Plans/operation/findPlans

sth like 
```yaml
- name: Create new device in a project
  hosts: localhost
  tasks:
    - equinix.cloud.metal_plan_info:
       categories: ["aaa", "bb", "vv"]
       type: "sometype"
       slug: "m3.small"   
      register: selected_plans
    - name: Print plans
      ansible.builtin.debug:
        msg: {{ selected_plans.resources }}

    - equinix.cloud.metal_plan_info:  
        # calls find_plans_by_project. project_id conflicts with categories, type and slug   
        project_id: "{{ test_project.id}}"
      register: project_available_plans
    - name: Print project plans
      ansible.builtin.debug:
        msg: {{ project_available_plans.resources }}
```
